name: Deploy to Render

on:
  push:
    branches:
      - main  # Thay 'main' bằng nhánh bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cqp0podds78s73e275og?key=ARlic2XFAzA"