name: Build & Deploy to Render

on:
  push:
    branches:
      - main  # Thay 'main' bằng nhánh bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # Hoặc yarn install nếu dùng Yarn

      - name: Build project
        run: npm run build  # Build ra thư mục dist/

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SRV }}?key=${{ secrets.RENDER_KEY }}"
